version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /home/ubuntu/yii-docker-stack/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - yii-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  frontend:
    image: amanagraw35/yii-frontend:latest
    networks:
      - yii-network
    depends_on:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  backend:
    image: amanagraw35/yii-backend:latest
    networks:
      - yii-network
    depends_on:
      - mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: yii_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - yii-network
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  yii-network:
    driver: overlay

volumes:
  mysql-data:
