version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"    # expose nginx on host port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # mount your nginx config here (adjust path)
    networks:
      - yii-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  frontend:
    image: amanagraw35/yii-frontend:latest
    # Remove ports mapping here, nginx will proxy requests
    networks:
      - yii-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - backend

  backend:
    image: amanagraw35/yii-backend:latest
    # Remove ports mapping here
    networks:
      - yii-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: yii_db
    volumes:
      - mysql-data:/var/lib/mysql
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - yii-network

networks:
  yii-network:
    driver: overlay

volumes:
  mysql-data:
