version: '3.2'

services:

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - 20080:80
    volumes:
      - composer-cache:/root/.composer/cache:delegated
      - .:/app

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - 21080:80
    volumes:
      - composer-cache:/root/.composer/cache:delegated
      - .:/app

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=yii2advanced
      - MYSQL_USER=yii2advanced
      - MYSQL_PASSWORD=secret

volumes:
  composer-cache:
