version: '3.8'

services:
  frontend:
    image: amanagraw35/yii-frontend:latest
    ports:
      - "8080:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - yii-network
    depends_on:
      - backend

  backend:
    image: amanagraw35/yii-backend:latest
    ports:
      - "8081:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - yii-network
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: yii_db
    volumes:
      - mysql-data:/var/lib/mysql
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - yii-network

networks:
  yii-network:
    driver: overlay

volumes:
  mysql-data:
