- name: Setup Docker Swarm and deploy Yii2 stack with NGINX container
  hosts: web
  become: true
  vars:
    stack_dir: /home/ubuntu/yii-docker-stack
    nginx_conf_src: ../nginx.conf
    nginx_conf_dest: "{{ stack_dir }}/nginx.conf"

  tasks:
    - name: Install required packages
      apt:
        name:
          - docker.io
          - docker-compose
          - git
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Initialize Docker Swarm (ignore if already initialized)
      shell: docker swarm init || true

    - name: Create stack directory
      file:
        path: "{{ stack_dir }}"
        state: directory
        mode: '0755'

    - name: Copy nginx.conf to stack directory
      copy:
        src: "{{ nginx_conf_src }}"
        dest: "{{ nginx_conf_dest }}"
        mode: '0644'

    - name: Copy docker-stack.yml to stack directory
      copy:
        src: ../docker-stack.yml
        dest: "{{ stack_dir }}/docker-stack.yml"
        mode: '0644'

    - name: Deploy Docker stack
      shell: docker stack deploy -c docker-stack.yml yii-app
      args:
        chdir: "{{ stack_dir }}"
