name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Frontend
        run: |
          docker build -t amanagraw35/yii-frontend:latest ./frontend
          docker push amanagraw35/yii-frontend:latest

      - name: Build & Push Backend
        run: |
          docker build -t amanagraw35/yii-backend:latest ./backend
          docker push amanagraw35/yii-backend:latest

      - name: SSH and Update Docker Swarm Stack
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/yii-app
            docker pull amanagraw35/yii-frontend:latest
            docker pull amanagraw35/yii-backend:latest
            docker stack deploy -c docker-stack.yml yii-app
