name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Frontend
        run: |
          docker build -t amanagraw35/yii-frontend:latest ./frontend
          docker push amanagraw35/yii-frontend:latest

      - name: Build & Push Backend
        run: |
          docker build -t amanagraw35/yii-backend:latest ./backend
          docker push amanagraw35/yii-backend:latest

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Create inventory file
        run: |
          echo "[web]" > inventory.ini
          echo "${{ secrets.EC2_HOST }} ansible_user=${{ secrets.EC2_USER }} ansible_ssh_private_key_file=key.pem" >> inventory.ini

      - name: Run Ansible Playbook
        run: |
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory.ini ansible/playbook.yml

      - name: SSH and Deploy Docker Stack
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ -d ~/yii-app ]; then
              cd ~/yii-app
            else
              echo "Directory ~/yii-app does not exist"
              exit 1
            fi

            if [ -f docker-stack.yml ]; then
              sudo docker pull amanagraw35/yii-frontend:latest
              sudo docker pull amanagraw35/yii-backend:latest
              sudo docker stack deploy -c docker-stack.yml yii-app
            else
              echo "docker-stack.yml file not found"
              exit 1
            fi
